---
# tasks file for easypki

- name: Create PKIs
  include_tasks: create_pkis.yml
  vars: 
    pki: "{{ pki_item.value }}"
    pki_name: "{{ pki_item.key }}"
  loop: "{{ easypki_chains | dict2items }}"
  loop_control:
    label: "{{ pki_item.key }}"
    loop_var: pki_item